//> using repository jitpack
//> using scala 3.7.0
//> using dep com.github.lichess-org.scalachess::scalachess:17.9.6-RC1
//> using dep org.typelevel::cats-effect:3.6.3
//> using dep co.fs2::fs2-io:3.12.0
//> using dep org.gnieh::fs2-data-csv:1.12.0
//> using dep org.gnieh::fs2-data-csv-generic:1.12.0
//> using dep org.typelevel::cats-parse::1.1.0
//> using dep com.lihaoyi::os-lib:0.11.5
//> using dep com.disneystreaming::weaver-cats:0.8.4
//> using testFramework weaver.framework.CatsEffect
