//> using scala "3.3.0-RC3"
//> using repository "https://raw.githubusercontent.com/lichess-org/lila-maven/master"
//> using lib "org.lichess::scalachess:14.8.0"
//> using lib "org.typelevel::toolkit::latest.release"
//> using lib "org.typelevel::cats-parse:0.3.9"
//> using lib "com.lihaoyi::os-lib:0.9.1"
//> using lib "com.disneystreaming::weaver-cats:0.8.1"
//> using testFramework "weaver.framework.CatsEffect"
