name: chess960-perft-22
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  chess960-perft-22:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
    - name: Test
      run: scala-cli test gen/Chess960PerftTests22.scala Common.scala