name: random-perft-279
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
    - main
  pull_request:

jobs:

  random-perft-279:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
    - name: Test
      run: scala-cli test -j 21 gen/RandomPerftTests279.scala Common.scala project.scala