name: tricky-perft-0
on:
  push:
    branches:
    - main
  pull_request:

jobs:

  tricky-perft-0:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
    - name: Test
      run: scala-cli test gen/TrickyPerftTests0.scala Common.scala project.scala